version: "2.2" 

services: 
  asir_bind:
    image: internetsystemsconsortium/bind9:9.16 
    ports:
      - 53:53
    volumes:
      - configure:/etc/bind
    networks: 
       br1:
        ipv4_address: 10.10.0.12
  asir_client:
    image: diegosierra/cliente_ubuntu:nettools
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    networks: 
       - br1
    dns:
       - 10.10.0.12
volumes:
    configure: 
networks:
  br1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1
          
